#!/usr/bin/env bash
# Local Airflow for trying Chappe against real Slack.
#
# Secrets and personal settings live in one file OUTSIDE the repo (default ~/.config/chappe/dev.env,
# permissions 600). Nothing secret is printed, written into the repo, or put on a command line.
#
#   scripts/dev-airflow.sh setup                  create the settings file (once), then edit it
#   scripts/dev-airflow.sh check                  validate the settings file and the generated config
#   scripts/dev-airflow.sh start                  stop leftovers, then run `airflow standalone`
#   scripts/dev-airflow.sh run pass|fail|parallel trigger the example scenarios (second terminal)
#   scripts/dev-airflow.sh password               print the local Airflow admin password
#   scripts/dev-airflow.sh stop                   stop every Airflow process of this repo
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${CHAPPE_DEV_ENV:-$HOME/.config/chappe/dev.env}"
VENV_BIN="$ROOT/.venv/bin"
export AIRFLOW_HOME="$ROOT/.airflow"
CONFIG="$AIRFLOW_HOME/chappe.dev.yaml"  # generated; .airflow/ is git-ignored

die() { echo "dev-airflow: $*" >&2; exit 1; }

need_venv() {
  [ -x "$VENV_BIN/airflow" ] || die "no .venv: run 'uv sync --all-groups' in $ROOT first"
}

# The settings file must exist, sit outside the repo and be readable by you only.
check_env_file() {
  [ -f "$ENV_FILE" ] || die "no settings file at $ENV_FILE: run '$0 setup' first"
  local real
  real="$(cd "$(dirname "$ENV_FILE")" && pwd)/$(basename "$ENV_FILE")"
  case "$real" in "$ROOT"/*) die "$ENV_FILE is inside the repo; keep it outside (default ~/.config/chappe/dev.env)" ;; esac
  local mode
  mode="$(stat -f %Lp "$ENV_FILE" 2>/dev/null || stat -c %a "$ENV_FILE")"
  [ "$mode" = "600" ] || die "$ENV_FILE has permissions $mode; run: chmod 600 $ENV_FILE"
}

# Reads the settings file (KEY=VALUE lines, never executed as shell), writes $CONFIG from the example
# with your channel and mention, and prints the connection JSON on stdout for the caller to capture.
settings() {
  "$VENV_BIN/python" - "$ENV_FILE" "$ROOT/examples/chappe.yaml" "$CONFIG" <<'PY'
import json, re, sys
from pathlib import Path

import yaml

env_file, example, target = map(Path, sys.argv[1:4])
values = {}
for number, line in enumerate(env_file.read_text(encoding="utf-8").splitlines(), 1):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    key, sep, value = line.partition("=")
    if not sep:
        sys.exit(f"dev-airflow: {env_file}:{number}: expected KEY=VALUE")
    values[key.strip()] = value.strip().strip("'\"")
missing = [k for k in ("SLACK_BOT_TOKEN", "SLACK_CHANNEL", "SLACK_MENTION") if not values.get(k)]
if missing:
    sys.exit(f"dev-airflow: {env_file}: set {', '.join(missing)}")
token = values["SLACK_BOT_TOKEN"]
if not token.startswith("xoxb-") or "REPLACE" in token:
    sys.exit(f"dev-airflow: {env_file}: SLACK_BOT_TOKEN must be your bot token (starts with xoxb-)")
if not re.fullmatch(r"[CG][A-Z0-9]{8,}", values["SLACK_CHANNEL"]):
    sys.exit(f"dev-airflow: {env_file}: SLACK_CHANNEL must be a channel ID (C… or G…), not #name")

config = yaml.safe_load(example.read_text(encoding="utf-8"))
process = config["chappe"]["processes"]["example"]
process["channel"] = values["SLACK_CHANNEL"]
process.setdefault("alerts", {})["mention"] = values["SLACK_MENTION"]
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(
    "# Generated by scripts/dev-airflow.sh from examples/chappe.yaml; edits are overwritten.\n"
    + yaml.safe_dump(config, sort_keys=False, allow_unicode=True),
    encoding="utf-8",
)
print(json.dumps({"conn_type": "generic", "password": token}))
PY
}

base_env() {
  export PATH="$VENV_BIN:$PATH"
  export CHAPPE_CONFIG="$CONFIG"
  export AIRFLOW__CORE__DAGS_FOLDER="$ROOT/examples/dags"
  export AIRFLOW__CORE__LOAD_EXAMPLES=False
  export AIRFLOW__CORE__SENSITIVE_VAR_CONN_NAMES=chappe
  export AIRFLOW__SECRETS__USE_CACHE=False
  # macOS: Slack calls from the forked DAG-processor child crash without these
  export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES no_proxy='*'
}

cmd_setup() {
  if [ -f "$ENV_FILE" ]; then
    echo "Settings file already exists: $ENV_FILE"
  else
    mkdir -p "$(dirname "$ENV_FILE")"
    (umask 077 && cat > "$ENV_FILE" <<'EOF'
# Chappe local testing. Keep this file outside the repo, permissions 600. Never commit it.
SLACK_BOT_TOKEN=xoxb-REPLACE-ME
SLACK_CHANNEL=C0123456789
SLACK_MENTION=<@U0123456789>
EOF
    )
    chmod 600 "$ENV_FILE"
    echo "Created $ENV_FILE (permissions 600)."
  fi
  echo "Edit it: your bot token, the test channel ID (bot invited), your mention. Then: $0 check"
}

cmd_check() {
  need_venv
  check_env_file
  settings >/dev/null
  "$VENV_BIN/chappe" validate-config "$CONFIG"
  echo "OK: $ENV_FILE is valid and $CONFIG was generated."
}

cmd_stop() {
  pkill -f "$VENV_BIN/airflow" 2>/dev/null || true
  for _ in 1 2 3 4 5; do
    pgrep -f "$VENV_BIN/airflow" >/dev/null || { echo "No Airflow process left."; return 0; }
    sleep 1
  done
  echo "Forcing the remaining Airflow processes to stop."
  pkill -9 -f "$VENV_BIN/airflow" 2>/dev/null || true
}

cmd_start() {
  need_venv
  check_env_file
  local conn
  conn="$(settings)"
  "$VENV_BIN/chappe" validate-config "$CONFIG" >/dev/null
  cmd_stop
  base_env
  export AIRFLOW_CONN_CHAPPE_SLACK="$conn"
  unset conn
  echo "Starting Airflow at http://localhost:8080 (admin password: $0 password). Ctrl-C stops it."
  exec airflow standalone
}

cmd_run() {
  need_venv
  base_env
  case "${1:-}" in
    pass) airflow dags trigger chappe_example ;;
    fail) airflow dags trigger chappe_example --conf '{"fail": true}' ;;
    parallel) airflow dags trigger chappe_example && airflow dags trigger chappe_example ;;
    *) die "usage: $0 run pass|fail|parallel" ;;
  esac
}

cmd_password() {
  local file="$AIRFLOW_HOME/simple_auth_manager_passwords.json.generated"
  [ -f "$file" ] || die "no password yet: start Airflow once with '$0 start'"
  cat "$file"; echo
}

case "${1:-}" in
  setup) cmd_setup ;;
  check) cmd_check ;;
  start) cmd_start ;;
  stop) cmd_stop ;;
  run) shift; cmd_run "$@" ;;
  password) cmd_password ;;
  *) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
